name: Azure Static Web Apps CI/CD - Phase 1

on:
  push:
    branches:
      - phase-1-infrastructure-setup
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - phase-1-infrastructure-setup

# Prevent concurrent deployments for stability
concurrency:
  group: phase-1-deployment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: 'npm'

      - name: Clean install to fix Rollup optional dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps

      - name: Pre-deployment cleanup
        run: |
          echo "Starting deployment for Phase 1"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        timeout-minutes: 10
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PORTFOLIO_3D_INTERACTIVE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'
          output_location: 'dist'

      - name: Deployment Success
        if: success()
        run: |
          echo "✅ Phase 1 deployment completed successfully"
          echo "🌐 Site URL: https://kind-flower-01e3e580f.2.azurestaticapps.net"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PORTFOLIO_3D_INTERACTIVE }}
          action: 'close'
