name: Performance Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  lighthouse:
    name: Lighthouse Performance Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Serve application
        run: |
          npm run preview &
          sleep 10  # Wait for server to start

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './.lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true

  bundle-analysis:
    name: Bundle Size Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and analyze bundle
        run: |
          npm run build
          npx vite-bundle-analyzer dist --open false --static dist/bundle-report.html

      - name: Upload bundle analysis
        uses: actions/upload-artifact@v3
        with:
          name: bundle-analysis
          path: dist/bundle-report.html

      - name: Check bundle size limits
        run: |
          # Get main bundle size
          MAIN_SIZE=$(du -b dist/assets/*.js | sort -n | tail -1 | cut -f1)
          MAIN_SIZE_KB=$((MAIN_SIZE / 1024))
          
          echo "Main bundle size: ${MAIN_SIZE_KB}KB"
          
          # Fail if main bundle is larger than 500KB
          if [ $MAIN_SIZE_KB -gt 500 ]; then
            echo "❌ Main bundle size (${MAIN_SIZE_KB}KB) exceeds limit (500KB)"
            exit 1
          else
            echo "✅ Bundle size is within limits"
          fi

  performance-budget:
    name: Performance Budget Check
    runs-on: ubuntu-latest
    needs: lighthouse
    
    steps:
      - name: Download lighthouse results
        uses: actions/download-artifact@v3
        with:
          name: lighthouse-ci-results

      - name: Check performance budget
        run: |
          echo "Performance budget checks would go here"
          echo "This could include checking Lighthouse scores against thresholds"
          echo "and failing the build if performance degrades significantly"
